AustinMcLean/AuSam

- css/styles.css
- index.html
- fixed img src path 
- centered and sized image 
- colour tweaks
> fixed img src path + centered and sized image + colour tweaks

- css/styles.css
- index.html
Updated nav bar, 
-Replaced text "Index" with "Home"
-Added an underline on hover
> Updated nav bar

- css/styles.css
- html/info.html
- index.html
- Added rsvp button and wedding day schedule to homepage
- Fixed relative path from info.html back to index.html
> Improve home page

- css/styles.css
- html/photos.html
- index.html
Created photos.html file and updated styles.css to have working A&S Photos tab.
Changed the css selector for the image on the home screen (was "img ", is now "#home-image") so it will only affect the image on index.html, and not all img tags throughout the code.
> add_photos

- css/styles.css
- html/info.html
- html/itinerary.html
- index.html
Added Itinerary page
Updated info page with Sam's wedding document
> Updated 3 day itinerary and info page

- Django_Demo/demo/myapp/templates/home.html
- Fixed image on homepage, now with variable link so it works from anywhere on the site
- RSVP button now redirects to rsvp page properly
> Fixed image on homepage +  RSVP button now redirects to rsvp page

- Django_Demo/demo/demo/settings.py
- Django_Demo/demo/myapp/generate_password.py
- Django_Demo/demo/myapp/middleware.py
- Django_Demo/demo/myapp/templates/password_entry.html
- Django_Demo/demo/myapp/urls.py
- Django_Demo/demo/myapp/views.py
- Added basic password functionality, using temporary development password
- This is one password for all users gating access to the whole site
> Added basic password functionality to website

- Django_Demo/demo/myapp/static/css/styles.css
- Django_Demo/demo/myapp/templates/password_entry.html
- Django_Demo/demo/myapp/templates/rsvp.html
- Made password input prompt nicer looking
- Put attending buttons on the same line and fixed size and hover
- Made "Incorrect password" error message bold and red for visibility
> Make password entry nicer

- Django_Demo/demo/myapp/static/css/styles.css
- Django_Demo/demo/myapp/templates/base.html
- Django_Demo/demo/myapp/templates/directions.html
- Django_Demo/demo/myapp/templates/home.html
- Django_Demo/demo/myapp/templates/info.html
- Django_Demo/demo/myapp/templates/itinerary.html
- Django_Demo/demo/myapp/templates/photos.html
- Django_Demo/demo/myapp/templates/rsvp.html
- Django_Demo/demo/myapp/urls.py
- Django_Demo/demo/myapp/views.py
Updated templates to work with Django.
> Template updates

- Django_Demo/demo/demo/settings.py
- Django_Demo/demo/myapp/views.py
- Added session timeout 60 minutes. Password will be required again after wither that amount of time, or if the webpage is closed.
> Added session timeout

- main_app/views.py
- updated password to actual one that will be used in prod
- now storing it's hashed value in an environment variable for added security
> Updated password & storred it's hash in an env var

- main_app/static/css/styles.css
- main_app/templates/base.html
- Added bootstrap burger menu for smaller screens
- named old navBar to navbar-original
> Added bootsrap burger menu, to be used on small screens

- main_app/static/css/styles.css
- main_app/templates/base.html
- Added media queries to improve performance on smaller screens, namely mobile
- Added additional my-container class name to avoid confusion with Bootstrap container keyword
- Some additional styling fixes to support these changes
> Added media queries for directions and name modal

- main_app/static/css/styles.css
- main_app/templates/rsvp.html
- Made invite fetching error message more visually appealing
- Moved error message styling to styles.css
> Made invite fetching error message nicer

- main_app/templates/rsvp.html
- Changed "N/A" meal option to "meat"
- Removed form-container form to avoid nesting forms, because apparently html doesn't like that very much
- Dynamically adding required tag to questions 
- Tweaked form validation accordingly
- Renamed child form variables for clarity as they're no longer subforms
> Removed nested forms & dynamic requirement of certain questions based on the response to others

- main_app/templates/rsvp.html
- Fixed initialisation of babysitter question by calling handler after form is appended to container
> Fixed initial state setting on babysitter question

- main_app/views.py
- Made invite fetching case insensitive using iexact lookup
> Made invite fetching case insensitive

- main_app/templates/base.html
- Removed Capture our Love from the navbars, as we're no longer using it
> Removed Capture our Love from navbars

- main_app/models.py
- site_config/settings/settings_base.py
- Added automatic email notifications for database entry modification, via SMTP using SendGrid add-on
> Added email notifications for changes to database entries

- main_app/static/css/styles.css
- main_app/templates/home.html
- main_app/templates/info.html
- main_app/templates/itinerary.html
- Updated info page, 3 day itinerary, and home page
- Added minor styling
> Updated information on site
